server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: products
          uri: https://dummyjson.com/products
          predicates:
            - Path=/products
          filters:
            - StripPrefix=0

  graphql:
    graphiql:
      enabled: true


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    propagation:
      type: b3
  endpoints:
    web:
      exposure:
        include: "*"