spring:
  application:
    name: movies-info-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: movie

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"